"""
Constants for secrets management environment variable names.

These constants define the environment variable names used to configure
secrets management across different platforms (AWS, Vault, Doppler).
"""

# Discord secret environment variable names
SECRETS_AWS_DISCORD_SECRET_NAME = 'SECRETS_AWS_DISCORD_SECRET_NAME'
SECRETS_VAULT_DISCORD_SECRET_PATH = 'SECRETS_VAULT_DISCORD_SECRET_PATH'
SECRETS_DOPPLER_DISCORD_SECRET_NAME = 'SECRETS_DOPPLER_DISCORD_SECRET_NAME'

# Matrix secret environment variable names
SECRETS_AWS_MATRIX_SECRET_NAME = 'SECRETS_AWS_MATRIX_SECRET_NAME'
SECRETS_VAULT_MATRIX_SECRET_PATH = 'SECRETS_VAULT_MATRIX_SECRET_PATH'
SECRETS_DOPPLER_MATRIX_SECRET_NAME = 'SECRETS_DOPPLER_MATRIX_SECRET_NAME'

# Bluesky secret environment variable names
SECRETS_AWS_BLUESKY_SECRET_NAME = 'SECRETS_AWS_BLUESKY_SECRET_NAME'
SECRETS_VAULT_BLUESKY_SECRET_PATH = 'SECRETS_VAULT_BLUESKY_SECRET_PATH'
SECRETS_DOPPLER_BLUESKY_SECRET_NAME = 'SECRETS_DOPPLER_BLUESKY_SECRET_NAME'

# Mastodon secret environment variable names
SECRETS_AWS_MASTODON_SECRET_NAME = 'SECRETS_AWS_MASTODON_SECRET_NAME'
SECRETS_VAULT_MASTODON_SECRET_PATH = 'SECRETS_VAULT_MASTODON_SECRET_PATH'
SECRETS_DOPPLER_MASTODON_SECRET_NAME = 'SECRETS_DOPPLER_MASTODON_SECRET_NAME'

# Threads secret environment variable names
SECRETS_AWS_THREADS_SECRET_NAME = 'SECRETS_AWS_THREADS_SECRET_NAME'
SECRETS_VAULT_THREADS_SECRET_PATH = 'SECRETS_VAULT_THREADS_SECRET_PATH'
SECRETS_DOPPLER_THREADS_SECRET_NAME = 'SECRETS_DOPPLER_THREADS_SECRET_NAME'

# Twitch secret environment variable names
SECRETS_AWS_TWITCH_SECRET_NAME = 'SECRETS_AWS_TWITCH_SECRET_NAME'
SECRETS_VAULT_TWITCH_SECRET_PATH = 'SECRETS_VAULT_TWITCH_SECRET_PATH'
SECRETS_DOPPLER_TWITCH_SECRET_NAME = 'SECRETS_DOPPLER_TWITCH_SECRET_NAME'

# YouTube secret environment variable names
SECRETS_AWS_YOUTUBE_SECRET_NAME = 'SECRETS_AWS_YOUTUBE_SECRET_NAME'
SECRETS_VAULT_YOUTUBE_SECRET_PATH = 'SECRETS_VAULT_YOUTUBE_SECRET_PATH'
SECRETS_DOPPLER_YOUTUBE_SECRET_NAME = 'SECRETS_DOPPLER_YOUTUBE_SECRET_NAME'

# Kick secret environment variable names
SECRETS_AWS_KICK_SECRET_NAME = 'SECRETS_AWS_KICK_SECRET_NAME'
SECRETS_VAULT_KICK_SECRET_PATH = 'SECRETS_VAULT_KICK_SECRET_PATH'
SECRETS_DOPPLER_KICK_SECRET_NAME = 'SECRETS_DOPPLER_KICK_SECRET_NAME'
